services:
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo_db
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_PASSWORD}@mongo_db:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    build: .
    depends_on:
      - mongo_db
    restart: always
    environment:
      DB_NAME: clientsDB
      MONGODB_URL: mongodb://root:${MONGO_PASSWORD}@mongo_db:27017/

  nginx:
    image: nginx:1.27.1-alpine
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
